name = "UnderwaterAcoustics"
uuid = "0efb1f7a-1ce7-46d2-9f48-546a4c8fbb99"
authors = ["Mandar Chitre <mandar@nus.edu.sg>"]
version = "0.1.2"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SignalAnalysis = "df1fea92-c066-49dd-8b36-eace3378ea47"

[compat]
Colors = "0.12"
DSP = "0.6, 0.7"
DifferentialEquations = "6.16, 7.0"
DocStringExtensions = "0.8"
FFTW = "1.3"
ForwardDiff = "0.10"
Interpolations = "0.13"
Optim = "1.2"
RecipesBase = "1.1"
Requires = "1.0"
SignalAnalysis = "0.4"
julia = "1.5"
